### ISSUE TITLE
pure boilerplate crashes the editor

### ISSUE THREAD

**Issue by caraffa** [VisualComposer/elementBoilerplate#3]
Step to reproduce:
1) Install and activate the vcwb demo plugin (https://github.com/VisualComposer/vcwb-demo-element-example-plugin)
2) download, install and build the vcwb-element-boilerplate **_without any modification_**
3) In Wordpress, open the VisualComposer editor
4) Click the "plus" sign (Add element)
5) Click the "Element Boilerplate" in the sidebar

Expected result:
The element is added to the row/column in the page

Real behaviour:
As soon as the "Add element" sidebar is opened in the editor, the console is populated with the following errors:
- 404 not found
- Cannot read property 'top' of undefined

As soon as you click the "Element Boilerplate", the console is populated with the following errors:
- Failed to find Element {...}
- cannot read property boilerplateColorMixin of undefined (twice)

and the editor crashes (becomes irresponsive)

See attached file for detailed error text:
[cannot read property of undefined.txt](https://github.com/VisualComposer/vcwb-element-boilerplate/files/2667632/cannot.read.property.of.undefined.txt)

**Comment by caraffa** [comment]
Some progress. I've found the problem, at least for the mixin part.
In the index.js file you have:

```
vcvAddElement(
  require('./settings.json'),
  // Component callback
  function (component) {
    component.add(ElementBoilerplate)
  },
  // css settings // css for element
  {
    css: false,
    editorCss: require('raw-loader!./editor.css'),
    cssMixins: { // <<------------------------
      boilerplateColorMixin: {
        mixin: require('raw-loader!./cssMixins/boilerplateColorMixin.pcss')
      }
    }
  }
)

```

You should change `cssMixins: {` to `mixins: {`

Now the element doesn't crash the editor, the element is loaded and can be inserted in the page, but now I have this other css error:

Failed to compile css

Detailed console output here 
[console.txt](https://github.com/VisualComposer/vcwb-element-boilerplate/files/2669307/console.txt)

Apparently pcss is not correctly configured

**Comment by caraffa** [comment]
The pcss code is broken. The "parent" (&) operator cannot be nested.
This is the correct one:
```
.vce-element-boilerplate-block{
  &--color-$selector {
    color: $textColor;
  }
  &--color-$selector:hover {
    color: color($textColor shade(10%));
  }
}

```

**Comment by pavelthq** [comment]
@caraffa Please check the latest updates, also note that repository name for consistancy also changed to "camelCase"
